### ISSUE TITLE
demonstrate multi-page use with an example

### ISSUE THREAD

**Issue by johnyf** [johnyf/pycflow2dot#1]
Add an example for how to create a multi-page PDF, and document the necessary LaTeX packages and setup.

**Comment by mhmayyan** [comment]
Hey,
I am using Ubuntu 18. I installed cflow and graphviz.

When I try "cflow2dot -i hello_simple.c -f png", I get the following 

digraph sarien {
node [shape=box];edge [color=black style=solid];


Any help, please?

**Comment by johnyf** [comment]
The OP https://github.com/johnyf/pycflow2dot/issues/1#issue-201718128 has been addressed in d3b8c332730a2fa57b5f53d903f0604d39a2c77b.
