### ISSUE TITLE
Generated output different than the provided example

### ISSUE THREAD

**Issue by z33kz33k** [johnyf/pycflow2dot#8]
I installed `pycflow2dot 0.2.1` via `pip` on `Ubuntu 16.04 LTS` with `cflow` and `dot`, but got results different than the provided example (using the same commands) - in the generated graphs there are no colors and no numbers under functions' names. Also when typing `clow2dot -h` in a terminal I don't see any relevant option that I should maybe turn on to get colors and numbers (that I'm assuming are functions' line count). Any ideas on what I'm doing wrong?

**Comment by Goldenstarc** [comment]
its like ads !

**Comment by johnyf** [comment]
Thank you for reporting this behavior. As of 4a043ea045a4b6348a06e6c27ce41751bc9ded28:

- The exporter that uses the function `networkx.drawing.nx_pydot.to_pydot` and `pydot` does not generate graphs with color and line numbers under function names.
- The exporter `dump_dot_wo_pydot` that dumps `dot` directly, without using `pydot`, does generate graphs with color and line numbers under function names. This exporter is called when `pydot` is not installed (in which case `pydot is None` below).

https://github.com/johnyf/pycflow2dot/blob/4a043ea045a4b6348a06e6c27ce41751bc9ded28/pycflow2dot.py#L344-L366

**Comment by johnyf** [comment]
Addressed in 3d54a67432a4838a55fa56978d33eb75f0f28d3f.
